import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { ProjectItem } from "~/components/projectItem";
import { ExperienceRecord } from "~/components/experienceRecord";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chris Nguyen</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col px-96">
        <nav>
          <ul className="flex justify-end gap-3 px-4 pb-10 pt-4">
            {/* <li>About</li>
            <li>Experience</li>
            <li>Projects</li>
            <li>Blog</li> */}
          </ul>
        </nav>

        <div className="flex flex-col">
          <header>
            <h1 className="text-4xl font-bold text-slate-200">Chris Nguyen</h1>
            <h2 className="normal-case">Full Stack Software Developer</h2>
            <p className="mt-6">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            {/* <ul className="mt-8 flex gap-4">
              <li>
                <Link target="_blank" href={"https://github.com/chrisnguyens2"}>
                  <Image
                    src={"/github.svg"}
                    alt="GitHub"
                    height={25}
                    width={25}
                  />
                </Link>
              </li>
              <li>
                <Link
                  target="_blank"
                  href={"https://www.linkedin.com/in/chrisnguyens2"}
                >
                  <Image
                    src={"/linkedin.svg"}
                    alt="LinkedIn"
                    height={25}
                    width={25}
                  />
                </Link>
              </li>
              <li>
                <Link
                  target="_blank"
                  href={"https://www.instagram.com/chris.nguyens/"}
                >
                  <Image
                    src={"/instagram.svg"}
                    alt="Instagram"
                    height={25}
                    width={25}
                  />
                </Link>
              </li>
            </ul> */}
          </header>

          <section>
            <h2>About</h2>
            <p className="pt-10">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue
              eu consequat ac felis donec et odio pellentesque. At consectetur
              lorem donec massa sapien faucibus. Ultrices sagittis orci a
              scelerisque purus semper eget. Id consectetur purus ut faucibus
              pulvinar elementum integer enim neque.
            </p>
          </section>

          <section>
            <h2>Experience</h2>
            <ol>
              <ExperienceRecord
                startDate={"August 2022"}
                endDate={"Present"}
                websiteUrl={
                  "https://www.hcss.com/products/gps-tracking-devices/"
                }
                company={"HCSS"}
                positionTitle={"Software Developer II"}
                positionDesc={
                  "Congue eu consequat ac felis donec et odio pellentesque. At consectetur lorem donec massa sapien faucibus. Ultrices sagittis orci a scelerisque purus semper eget. Id consectetur purus ut faucibus pulvinar elementum integer enim neque."
                }
                technologiesUsed={[
                  "React",
                  "TypeScript",
                  ".NET",
                  "C#",
                  "Azure",
                  "SQL",
                  "Terraform",
                  "Grafana",
                ]}
              />
              <ExperienceRecord
                startDate={"June 2021"}
                endDate={"August 2022"}
                websiteUrl={
                  "https://www.hcss.com/products/gps-tracking-devices/"
                }
                company={"HCSS"}
                positionTitle={"Software Developer"}
                positionDesc={
                  "Congue eu consequat ac felis donec et odio pellentesque. At consectetur lorem donec massa sapien faucibus. Ultrices sagittis orci a scelerisque purus semper eget. Id consectetur purus ut faucibus pulvinar elementum integer enim neque."
                }
                technologiesUsed={[
                  "React",
                  "TypeScript",
                  ".NET",
                  "C#",
                  "Azure",
                  "SQL",
                ]}
              />
            </ol>
          </section>

          <section>
            <h2>Projects</h2>
            <ul className="pt-10">
              <ProjectItem
                imageUrl={"/twitter_clone_page.png"}
                websiteUrl={"https://twitter-clone-khaki-six.vercel.app/"}
                name={"Twitter Clone"}
                description={
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue eu consequat ac felis donec et odio pellentesque. At consectetur"
                }
                technologiesUsed={["Next.js","Tailwind CSS","Prisma","tRPC"]}
              />
              <ProjectItem
                imageUrl={"/chris_nguyen_portfolio.png"}
                websiteUrl={"https://chris-nguyen-portfolio.vercel.app/"}
                name={"Chris Nguyen Portfolio"}
                description={
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue eu consequat ac felis donec et odio pellentesque. At consectetur"
                }
                technologiesUsed={["Next.js","Tailwind CSS"]}
              />
            </ul>
          </section>

          <section>
            <h2>Blog</h2>
            <ol>
              <li>
                <a className="mr-12 font-bold" href="">First Blog Post</a>
                <span>Dec 3, 2023</span>
              </li>
            </ol>
          </section>
        </div>

        <footer className="pt-24 pb-6">
          <hr></hr>
          <ul className="mt-6 flex gap-4 justify-end">
              <li>
                <Link target="_blank" href={"https://github.com/chrisnguyens2"}>
                  <Image
                    src={"/github.svg"}
                    alt="GitHub"
                    height={25}
                    width={25}
                  />
                </Link>
              </li>
              <li>
                <Link
                  target="_blank"
                  href={"https://www.linkedin.com/in/chrisnguyens2"}
                >
                  <Image
                    src={"/linkedin.svg"}
                    alt="LinkedIn"
                    height={25}
                    width={25}
                  />
                </Link>
              </li>
              <li>
                <Link
                  target="_blank"
                  href={"https://www.instagram.com/chris.nguyens/"}
                >
                  <Image
                    src={"/instagram.svg"}
                    alt="Instagram"
                    height={25}
                    width={25}
                  />
                </Link>
              </li>
            </ul>
        </footer>
      </main>
    </>
  );
}